# --------------------------------------------------------------------------------
#                                    LuckDataBase
# Atualmente o LuckCode dá suporte a 4 tipos de banco de dados, onde 2 deles são
# mais comumente usados por outros servidores (Mysqli e SQLite3), já os outros 2
# tipos também são do gênero SQL, porem a conexão deles é gerada utilizando o
# PDO (PhpDataObject), que por sua vez chega a ser mais rápido em certos pontos,
# porém não é toda a hospedagem que oferece o driver do PHP para dar suporte ao
# PDO. 
# Se lembre que é sempre viável utilizar por padrão o Mysqli ou SQLite3, afinal
# muitos plugins já o utilizam, no entanto caso opte por usar o PDO, seja ele
# Mysqli ou SQLite3 fique por sua conta e risco.
#
# Tipos disponíveis de banco de dados:
# 
# + SQLite3
# + Mysqli (requer autenticação)
# + PDO-SQLite3
# + PDO-Mysqli (requer autenticação)
# --------------------------------------------------------------------------------

# É possível estabelecer uma lista de execução de provedores para que o banco
# de dados funcione. Abaixo é possível mudar a ordem na qual o sistema vai
# tentar se conectar o provedor, se lembre que é comum ter erros de conexão com
# o banco Mysqli, neste caso sempre verifique as informações de autenticação
# na configuração.
# Caso nenhum dos provedores conseguirem iniciar o LuckCode vai desabilitar.
type_priority:
  - "mysqli"
  - "sqlite3"
  - "pdo-mysqli"
  - "pdo-sqlite3"

# Configure os campos abaixo caso for utilizar um provedor do tipo Mysqli. Algumas
# doferecida estas configurações como host, user e password geralmente são 
# oferecidas pela sua hospedagem, as vezes o dbname (ou “nome do banco de dados”) 
# também é oferecida por padrão já criada no banco de dados, mas caso não tenha 
# veja como criar uma (o que pode variar dependendo do tipo de painel que sua
# hospedagem oferece, mas caso seja o PhpMyAdmin: https://bit.ly/3nIvRnJ [1:20].
# PS: O link, usuário e senha de acesso ao painel do Mysqli devem ser oferecidos
# por sua hospedagem caso ela ofereça esse serviço). 
mysqli_auth:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  dbname: "luckCode"


# Defina se a tabela de testes do banco de dados esta ativa.
enable_test_table: true